### ISSUE TITLE
Define the teams

### ISSUE THREAD

**Issue by Filnor** [SOBotics/SoundFlow#2]
Currently, the [team list](https://github.com/SOBotics/SoundFlow/blob/master/soundflow/teams.py) is pretty empty. We should fill that with more of them. I already filled in where I'm completely sure.

**Comment by geisterfurz007** [comment]
Github Admins (ignore if that is the Admins list or add an alias for that) maybe?

**Comment by Filnor** [comment]
@geisterfurz007 I'd rather add it as an alias for now, and add an additonal team if needed. FWIW, the Admin Team is also not an official team per se.

**Comment by Filnor** [comment]
Wished by Petter Friberg: Head Detector team, with himself and geisterfurz007 in the team.

**Comment by Filnor** [comment]
Even though this is closed. You can still comment if you want to add another team.

**Comment by LunarWatcher** [comment]
Can we have a Redunda team and/or a team for general server management? 

Especially when Redunda goes down, it's kinda unclear who to ping (well, [aside NobodyNada](https://chat.stackoverflow.com/transcript/message/45113642#45113642) :p)

**Comment by Filnor** [comment]
We can do that, yes. Just need to know whom to add. I'd suggest Undo, since Redunda is running on their server

**Comment by LunarWatcher** [comment]
Looks like it's [just Undo](https://chat.stackexchange.com/transcript/message/48579516#48579516) (unless I misunderstood something). It's a start at least.
